### PR TITLE
Update from jdvsandt/LibGit

### PR DESCRIPTION
**Pull request by npasserini**

### CODE REVIEW

**Comment by npasserini** [comment]
Hi @jvdsandt, sorry I never merged your PR. The problem is that, due to the metadata changes, it produces several conflicts. In the meanwhile @theseion removed the metadata from his repository, and I merged that changes into mine. So I think that if we could merge that changes into your repository first, afterwards will be much easier to keep us synchronized. 

If you want I can make a pull request for your repo removing the metadata, do you agree?

**Comment by theseion** [comment]
@jvdsandt hasn't been active on GitHub since May. I suggest that I fork his repository, clean out the metadata and then issue a new pull request for you. How does that sound?

**Comment by jvdsandt** [comment]
Hi,

I'm still here. I can accept a PR but if you want to take another approach
that's also. fine.

Jan.

**Comment by npasserini** [comment]
It sounds great.

2016-10-23 19:48 GMT+02:00 Max Leske <notifications@github.com>:

**Comment by theseion** [comment]
I just wanted to make sure that we can get back to a single repository, and since I didn't see a response to Nico's question I thought I could help. Please go ahead with the PR, as Nico suggested.

**Pull request closed without merging**
